### ISSUE TITLE
Possible client-side incompatibility with MiniHUD

### ISSUE THREAD

**Issue by CodedSakura** [Patbox/StyledPlayerList#1]
It seems that the MiniHUD's TPS readout does not work while the TPS is displayed in the PlayerList. It started working once i switched to `/log tps` from carpetmod (Which overrode the StyledPlayerList tab menu).

By 'does not work' i mean that it says `Server TPS: <no valid data>` and sometimes flickers to showing the TPS, but going back to invalid data within a second.

**Comment by Patbox** [comment]
Hmm. SPL sends playerlist updates at the end of playerTick (which is normally used for synchronizing player data), so it might be causing it (I'm not sure why). But I will look into that.

**Comment by Patbox** [comment]
Okay, I've checked MiniHUD's code and it's issue that I can't fix. It looks like MiniHud tries to parse any Player List Header/Footer change as one from Carpet, which fails for any custom player list.

**Comment by CodedSakura** [comment]
Alright, i guess i'll report it to MiniHUD then!  
(Gonna keep this issue open until they fix it.)

**Comment by CodedSakura** [comment]
Already fixed in a MiniHUD pre-release.
