### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by A5ho9999** [Patbox/StyledPlayerList#14]
Does or can the player list support a custom image logo instead of the normal text title? If not, is this a possible feature that could be added?

**Comment by Trent2087** [comment]
We are using an image in the All of Fabric 6 Servers. Note that you must ship the assets with the client for this to work.
https://github.com/TeamAOF/All-of-Fabric-6/tree/main/kubejs/assets/aof
this is where the images are. Must be 256x256 or smaller. 
/textures/other/aof6_bannerA.png, aof6_bannerB.png, aof6_bannerC.png
and then you create a font that uses those images
/font/icons.json
Then in your server /config/styledplayerlist/styles/default.json you create a line with the custom font
"<font:'aof:icons'>.a.b.c</font>",
which will get you something like this.
![image](https://github.com/Patbox/StyledPlayerList/assets/132113621/605646e9-f1d8-41c6-aa40-4c68f9ee3fa4)
Hope this helps!

**Comment by A5ho9999** [comment]
Thanks! That helps alot!
