### ISSUE TITLE
1.20.1 don't correctly work

### ISSUE THREAD

**Issue by DonorKrovi** [Patbox/StyledPlayerList#16]
For some reason, version 1 20 1 does not display prefixes and other values in the player's TAB

![image](https://github.com/Patbox/StyledPlayerList/assets/60231586/c3b464aa-8cd4-451b-8036-a1f7cb558da4)

Config:

![image](https://github.com/Patbox/StyledPlayerList/assets/60231586/3334efb4-f675-4214-8735-174a1da338db)

I'm use:

Faction
banhammer
styledplayerlist 1.20.1-3.1.1+
advanced-chat
ordered-playerlist
styled-chat
player-heads

**Comment by Patbox** [comment]
Set modify_name to true
