### ISSUE TITLE
1.20.1 don't correctly work

### ISSUE THREAD

**Issue by DonorKrovi** [Patbox/StyledPlayerList#17]
https://github.com/Patbox/StyledPlayerList/issues/16

I did what you wrote and reloaded the mod, it didn't help and I decided to reboot the server, it didn't help either

**Comment by DonorKrovi** [comment]
![image](https://github.com/Patbox/StyledPlayerList/assets/60231586/69556cf8-9011-464e-90ac-50991fafc4ae)

**Comment by arnokeesman** [comment]
this is on my showcase server, factions breaks SPL on default config
![image](https://github.com/Patbox/StyledPlayerList/assets/34793978/2228f3af-6f30-44cb-a5e6-720e00d29346)
you can disable `factions.json`.`display`.`tabMenu` to fix it
![image](https://github.com/Patbox/StyledPlayerList/assets/34793978/a4965219-3ae4-4b99-8ad6-7bb26ba23914)
(also, you probably want to set `update_tick_time` in SPL to something like `20`)
if you do want the faction to show up in tab as well, they have placeholders [listed on their wiki](https://github.com/ickerio/factions/wiki/Display#placeholder-api)

**Comment by DonorKrovi** [comment]
Thanks!

**Comment by DonorKrovi** [comment]
> this is on my showcase server, factions breaks SPL on default config ![image](https://user-images.githubusercontent.com/34793978/270317785-2228f3af-6f30-44cb-a5e6-720e00d29346.png) you can disable `factions.json`.`display`.`tabMenu` to fix it ![image](https://user-images.githubusercontent.com/34793978/270318723-a4965219-3ae4-4b99-8ad6-7bb26ba23914.png) (also, you probably want to set `update_tick_time` in SPL to something like `20`) if you do want the faction to show up in tab as well, they have placeholders [listed on their wiki](https://github.com/ickerio/factions/wiki/Display#placeholder-api)

Now, after restarting the server, if you do not register a reboot of the mod, the prefixes will not be able to work

**Comment by arnokeesman** [comment]
Which prefixes?
This should've been fixed in 3.1.1
