### ISSUE TITLE
Problem with Vanish

### ISSUE THREAD

**Issue by dakiba** [Patbox/StyledPlayerList#18]
If you use the Mod [Vanish](https://www.curseforge.com/minecraft/mc-mods/vanish) the playerlist shows still the connected player count. Vanish is a mod that help to get "true" invisible for server admins (sadly we need that because we had cheater on our server). But the StyledPlayerList shows still the "correct" connected player count. So if you have 9 Player and 1 vanished (invisible) admin, the list shows 10 / X. But its works that the admin isn't in the Playerlist anymore.

**Comment by arnokeesman** [comment]
try [other vanish](https://modrinth.com/mod/vanish) it does have [integrations with SPL](https://placeholders.pb4.eu/user/mod-placeholders/#vanish)

**Comment by Kisuny** [comment]
> try [other vanish](https://modrinth.com/mod/vanish) it does have [integrations with SPL](https://placeholders.pb4.eu/user/mod-placeholders/#vanish)

same effect 
![image](https://github.com/Patbox/StyledPlayerList/assets/56004431/2bd3405d-04b7-4aa6-a56d-963388371e80)
![image](https://github.com/Patbox/StyledPlayerList/assets/56004431/a460e26a-47bf-4cde-85af-c9bf7e56a256)

**Comment by Tunga-Tech** [comment]
Ir doesn't work with that one either.

**Comment by Tunga-Tech** [comment]
> try [other vanish](https://modrinth.com/mod/vanish) it does have [integrations with SPL](https://placeholders.pb4.eu/user/mod-placeholders/#vanish)

It doesn't work with that one either.
