### ISSUE TITLE
Unable to remove Ping from displayname | 3.1.1+1.20.1

### ISSUE THREAD

**Issue by Roguevashda** [Patbox/StyledPlayerList#25]
On fabric for 1.20.1 using StyledPlayeList 3.1.1+1.20.1 I am unable to remove the ping from showing after people's displayname. There is no option in the configs nor is it a conflicting mod/plugin.

This was tested with nothing but the Fabric API and StyledPlayerList
![n9aJEZOAMo](https://github.com/user-attachments/assets/87533983-0e59-412c-a45e-a34430801a59)
![Ks0SpPSyUk](https://github.com/user-attachments/assets/046cbac6-c809-44e4-8c2f-7ccd46904281)

config is default except modify_name, which has been tested with and without being enabled.

```{
  "config_version": 2,
  "__comment": "Before changing anything, see https://github.com/Patbox/StyledPlayerList#configuration",
  "default_style": "default",
  "messages": {
    "switch": "Your player list style has been changed to: <gold>${style}</gold>",
    "unknown": "<red>This style doesn't exist!</red>",
    "no_permission": "<red>You don't have required permissions!</red>"
  },
  "player": {
    "modify_name": true,
    "passthrough": false,
    "hidden": false,
    "format": "%player:displayname%",
    "update_on_chat_message": false,
    "update_tick_time": 20,
    "styles": []
  },
  "client_show_in_singleplayer": true
}
```

**Comment by Patbox** [comment]
That ping number is provided by some other mod, not Styled Player List

**Comment by Roguevashda** [comment]
Apologies, you're correct. It was a client-side mod that came with the cobblemon modpack to change the ping bar into numbers and annoyingly enough the modpack has it also show the ping bar. 

Sorry for wasting your time.
