### ISSUE TITLE
How to remove spaces between death counter and better ping display

### ISSUE THREAD

**Issue by Kloytz** [Patbox/StyledPlayerList#26]
![image](https://github.com/user-attachments/assets/b6b20c50-f827-45c4-9c9b-143f86f295fd)

Also as an additional question, how can i make styled player list display health like with scoreboard command, because if i use %player:health% the health is displayed as numbers.

![image](https://github.com/user-attachments/assets/88f8ea2a-563b-4526-ba8c-992094ab5dd4)

**Comment by Patbox** [comment]
It happens because of a some client side mod you use, so I can't change it.
