### ISSUE TITLE
[Bug report] Placeholder %server:max_ram [gb]% displayed as MB instead of GB

### ISSUE THREAD

**Issue by Surgeol** [Patbox/StyledPlayerList#27]
**Minecraft server version:** 1.21
**Server mod loader:** Fabric 0.16.5
**Styled Player List version:** 3.5.1+1.21

**Problems:** I'm using this config to display my server mem usage on playlist. I want it would display in GB but the result is in MB, not sure if other users are meeting the same issue. I've searched through the issues but haven't found any related feedback.

```
<gray>Mem used(GB):</gray> %server:used_ram [gb]%GB / %server:max_ram [gb]%GB
<gray>Mem used(MB):</gray> %server:used_ram%MB / %server:max_ram%MB
```
![example](https://github.com/user-attachments/assets/d7e631e9-e628-4558-ac63-411b26e97b18)

**Comment by Patbox** [comment]
The [] are used to indicate it as optional argument, removing them should make it work

**Comment by Surgeol** [comment]
Yeah silly me, it works :(
Thanks for your help
