### ISSUE TITLE
fabric_loader_dependencies

### ISSUE THREAD

**Issue by PortableGames** [Patbox/StyledPlayerList#4]
don't really understand, can you create a fabric_loader_dependencies.json file for me that will fix the incompatibility?

I'm willing to support you with some matching funds for the job

**Comment by Tom-The-Geek** [comment]
The wiki article linked should have examples included, you just need to override the dependency on `minecraft` to be the version you need, or just remove it entirely. This also didn't require a new issue and could've been asked under #3

**Comment by PortableGames** [comment]
I don't really understand this stuff... if you do it, I'll reward you
