### ISSUE TITLE
Support for fabric tps, mspt, and mop cap variables

### ISSUE THREAD

**Issue by ZachTheDev** [Patbox/StyledPlayerList#7]
Would love the ability to use this mod along with fabric for modifying the player list and including the detailed information that fabric allows.

Thanks!

**Comment by Patbox** [comment]
It is already supported via https://placeholders.pb4.eu/user/default-placeholders/ or https://placeholders.pb4.eu/user/mod-placeholders/

**Comment by illiab9** [comment]
Doesn't work right now, or I'm dumb, and can't understand.

1.16.5

**Comment by Patbox** [comment]
Older version don't have all placeholders
